
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clientservice
  name: clientservice
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientservice
  strategy: {}
  template:
    metadata:
      labels:
        app: clientservice
    spec:
      containers:
      - image: mousse2025/client:197fb3be6ac4c9dd8645fe5f1254f31a5b5d298e
        name: client
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/client_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: clientservice
  name: clientservice
  namespace: demo-app
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: clientservice
  type: ClusterIP
